trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Use Python 3'

- script: |
    python -m pip install --upgrade pip
    pip install -r backend/requirements.txt
  displayName: 'Install Dependencies'

- script: |
    python -m unittest discover backend/tests
  displayName: 'Run Unit Tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'backend/api'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/flask-app.zip'
    replaceExistingArchive: true
  displayName: 'Package Flask API'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/flask-app.zip'
    artifactName: 'drop'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-azure-resume-connection'  # Use your Azure Service Connection
    appName: 'AzureWebAppForFlask'  # Use your Flask Web App name
    package: '$(Build.ArtifactStagingDirectory)/flask-app.zip'
  displayName: 'Deploy Flask API to Azure Web App'
