trigger:
- main  # Runs on push to main branch

pool:
  vmImage: ubuntu-latest  # Use Ubuntu for the pipeline

steps:
- task: AzureStaticWebApp@0  # Use Version 0 instead of 1
  inputs:
    app_location: 'frontend'  # Path where index.html is stored
    api_location: ''  # No API in Static Web App
    output_location: ''  # No build output
    azure_static_web_apps_api_token: $(deployment_token)  # Add Deployment Token
  displayName: 'Deploy Frontend to Azure Static Web App'
