trigger:
- main  # Runs on push to main branch

pool:
  name: 'LAPTOP-8MVSFPFT'  # Replace with your actual self-hosted agent pool name

steps:
- task: AzureStaticWebApp@0  # Using Version 0
  inputs:
    app_location: 'frontend'  # Path where index.html is stored
    api_location: ''  # No API in Static Web App
    output_location: ''  # No build output
    azure_static_web_apps_api_token: $(deployment_token)  # Add Deployment Token
  displayName: 'Deploy Frontend to Azure Static Web App'
