trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    addToPath: true

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the application'

- script: npm test
  displayName: 'Run tests'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'YOUR_AZURE_SERVICE_CONNECTION_NAME'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp deploy --resource-group myResourceGroup --name myAppName --src-path $(Build.ArtifactStagingDirectory)
  displayName: 'Deploy to Azure'
